### ISSUE TITLE
Multiple Lots response not allowed

### ISSUE THREAD

**Issue by ricardoreais** [ESPD/espd#220]
Currently in the documentation it is shown that we can have a TenderingCriterionResponse with multiple ResponseValues, but the validator doesn't allow it (Response (version 2.0.2))

![image](https://user-images.githubusercontent.com/22318105/54150578-afcbd180-4430-11e9-9afe-72cb7165f918.png)

**Comment by ec-mcs** [comment]
@ricardoreais could you post this in the EDM repository https://github.com/ESPD/ESPD-EDM/issues? Thx. I will close this issue here as this repository is about our ESPD service and not the ESPD data model.
