### ISSUE TITLE
Firma de documento

### ISSUE THREAD

**Issue by Derypol** [ESPD/espd#228]
Hola,

Al terminar de editar el DEUC no me deja firmarlo ya que no está operativa esta sección, ¿sabéis qué puedo hacer?. 

![Sin título](https://user-images.githubusercontent.com/59737401/72164177-80c21b80-33c5-11ea-8437-dafa6813edc7.png)

Gracias

**Comment by ec-mcs** [comment]
Hi Derypol,

If it is required from the buyer that you sign the ESPD, then there are two possibilities. The most common is to export it as a PDF and then to sign it. The other one is to export it as an XML and use an XML signature.

I will close this issue.

Best
