### ISSUE TITLE
Embed XML into PDF

### ISSUE THREAD

**Issue by softwarewerke** [ESPD/espd#230]
Hi, 

is there any chance to get the XML embedded into the PDF as result of 

https://visor.registrodelicitadores.gob.es/espd-web/

Thank you!

**Comment by ec-mcs** [comment]
To embed an XML into PDF is not a function of the ESPD service but can be achieved with PDF tools. Usually there is the option to embed a file (which can be PDF). Don't know if this can be done in the free version of Acrobat Reader.
